package com.irs.bean;

public class Orderxx {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_orderxx.xid
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	private Integer xid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_orderxx.oid
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	private String oid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_orderxx.pid
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	private Integer pid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_orderxx.gname
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	private String gname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_orderxx.num
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	private Integer num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_orderxx.gimage
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	private String gimage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_orderxx.gprice
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	private Double gprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_orderxx.gtotal
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	private Double gtotal;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_orderxx
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public Orderxx(Integer xid, String oid, Integer pid, String gname,
			Integer num, String gimage, Double gprice, Double gtotal) {
		this.xid = xid;
		this.oid = oid;
		this.pid = pid;
		this.gname = gname;
		this.num = num;
		this.gimage = gimage;
		this.gprice = gprice;
		this.gtotal = gtotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_orderxx
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public Orderxx() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_orderxx.xid
	 * @return  the value of t_orderxx.xid
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public Integer getXid() {
		return xid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_orderxx.xid
	 * @param xid  the value for t_orderxx.xid
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public void setXid(Integer xid) {
		this.xid = xid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_orderxx.oid
	 * @return  the value of t_orderxx.oid
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public String getOid() {
		return oid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_orderxx.oid
	 * @param oid  the value for t_orderxx.oid
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public void setOid(String oid) {
		this.oid = oid == null ? null : oid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_orderxx.pid
	 * @return  the value of t_orderxx.pid
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_orderxx.pid
	 * @param pid  the value for t_orderxx.pid
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_orderxx.gname
	 * @return  the value of t_orderxx.gname
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public String getGname() {
		return gname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_orderxx.gname
	 * @param gname  the value for t_orderxx.gname
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public void setGname(String gname) {
		this.gname = gname == null ? null : gname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_orderxx.num
	 * @return  the value of t_orderxx.num
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_orderxx.num
	 * @param num  the value for t_orderxx.num
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public void setNum(Integer num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_orderxx.gimage
	 * @return  the value of t_orderxx.gimage
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public String getGimage() {
		return gimage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_orderxx.gimage
	 * @param gimage  the value for t_orderxx.gimage
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public void setGimage(String gimage) {
		this.gimage = gimage == null ? null : gimage.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_orderxx.gprice
	 * @return  the value of t_orderxx.gprice
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public Double getGprice() {
		return gprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_orderxx.gprice
	 * @param gprice  the value for t_orderxx.gprice
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public void setGprice(Double gprice) {
		this.gprice = gprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_orderxx.gtotal
	 * @return  the value of t_orderxx.gtotal
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public Double getGtotal() {
		return gtotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_orderxx.gtotal
	 * @param gtotal  the value for t_orderxx.gtotal
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public void setGtotal(Double gtotal) {
		this.gtotal = gtotal;
	}
}