package com.irs.bean;

public class Role {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.rid
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	private Integer rid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.rname
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	private String rname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.remark
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public Role(Integer rid, String rname, String remark) {
		this.rid = rid;
		this.rname = rname;
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public Role() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.rid
	 * @return  the value of sys_role.rid
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public Integer getRid() {
		return rid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.rid
	 * @param rid  the value for sys_role.rid
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public void setRid(Integer rid) {
		this.rid = rid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.rname
	 * @return  the value of sys_role.rname
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public String getRname() {
		return rname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.rname
	 * @param rname  the value for sys_role.rname
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public void setRname(String rname) {
		this.rname = rname == null ? null : rname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.remark
	 * @return  the value of sys_role.remark
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.remark
	 * @param remark  the value for sys_role.remark
	 * @mbggenerated  Tue Jul 24 08:44:31 CST 2018
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}